//Session
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

//Admins
export const FETCH_ADMINS = "FETCH_ADMINS";

//Selected Candidates
export const CANDIDATE_ADD = "CANDIDATE_ADD";
export const CANDIDATE_REMOVE = "CANDIDATE_REMOVE";
export const CANDIDATES_SUBMIT_OR_EMPTY = "CANDIDATE_SUBMIT_OR_EMPTY";

//Candidates
export const FETCH_CANDIDATES = "FETCH_CANDIDATES";
export const FETCH_CANDIDATE_DETAILS = "FETCH_CANDIDATE_DETAILS";

//Job Postings
export const FETCH_JOB_POSTINGS = "FETCH_JOB_POSTINGS";
export const JOB_POSTING_SELECT = "JOB_POSTING_SELECT";
export const DELETE_JOBPOSTING = "DELETE_JOBPOSTING";

//Clients
export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const SELECT_CLIENT = "SELECT_CLIENT";
export const EMPTY_CLIENT = "EMPTY_CLIENT";

//Recruiters
export const FETCH_RECRUITERS = "FETCH_RECRUITERS";
export const SELECT_RECRUITER = "SELECT_RECRUITER";
export const EMPTY_RECRUITER = "EMPTY_RECRUITER";
